//includes
#include <MDR32Fx.h>
//init variable&contants
uint32_t Flag = 0;
//init function prototype

//main function
int main ()
{
	MDR_RST_CLK->PER_CLOCK = 0xFFFFFFFF;

MDR_PORTD -> OE |= (1 << 10)| (1 << 11)| (1 << 12)| (1 << 13)|(1 << 14);
MDR_PORTD -> FUNC |= (0x01 << PORT_FUNC_MODE10_Pos);
MDR_PORTD -> ANALOG |= (1 <<10);
MDR_PORTD -> PD &= ~ (1 << 10);
MDR_PORTD -> PWR |= (0x3 << PORT_PWR10_Pos);
MDR_TIMER1 -> ARR = 8000;
	

MDR_RST_CLK -> TIM_CLOCK |= (RST_CLK_TIM_CLOCK_TIM1_CLK_EN) |  (RST_CLK_TIM_CLOCK_TIM2_CLK_EN) ;	
MDR_TIMER1 -> CNTRL |= (1 << TIMER_CNTRL_ARRB_EN_Pos)| TIMER_CNTRL_CNT_EN;	
MDR_TIMER1 -> CH2_CNTRL1|= (0x2 << TIMER_CH_CNTRL1_SELO_Pos);
MDR_TIMER1 -> CH2_CNTRL1|= (0x01 << TIMER_CH_CNTRL1_SELOE_Pos);	
MDR_TIMER1 -> CH2_CNTRL |= (0x6 << TIMER_CH_CNTRL_OCCM_Pos);	
	

MDR_PORTD -> FUNC |= (0x2 << PORT_FUNC_MODE11_Pos);
MDR_PORTD -> ANALOG |= (1 <<11);
MDR_PORTD -> PD &= ~ (1 << 11);
MDR_PORTD -> PWR |= (0x3 << PORT_PWR11_Pos);
MDR_TIMER2 -> ARR = 8000;
	


MDR_TIMER2 -> CNTRL |= (1 << TIMER_CNTRL_ARRB_EN_Pos)| TIMER_CNTRL_CNT_EN;	
MDR_TIMER2 -> CH2_CNTRL1|= (0x2 << TIMER_CH_CNTRL1_NSELO_Pos);
MDR_TIMER2 -> CH2_CNTRL1|= (0x1 << TIMER_CH_CNTRL1_NSELOE_Pos);
MDR_TIMER2 ->CH2_CNTRL1 |= (0x1 << TIMER_CH_CNTRL1_NINV_Pos);	
MDR_TIMER2 -> CH2_CNTRL |= (0x6 << TIMER_CH_CNTRL_OCCM_Pos);	


MDR_PORTD -> FUNC |= (0x01 << PORT_FUNC_MODE12_Pos);
MDR_PORTD -> ANALOG |= (1 <<12);
MDR_PORTD -> PD &= ~ (1 << 12);
MDR_PORTD -> PWR |= (0x3 << PORT_PWR12_Pos);

	
//MDR_RST_CLK-> TIM_CLOCK = RST_CLK_TIM_CLOCK_TIM1_CLK_EN;		
MDR_TIMER1 -> CH3_CNTRL1|= (0x2 << TIMER_CH_CNTRL1_SELO_Pos);
MDR_TIMER1 -> CH3_CNTRL1|= (0x01 << TIMER_CH_CNTRL1_SELOE_Pos);	
MDR_TIMER1 -> CH3_CNTRL |= (0x6 << TIMER_CH_CNTRL_OCCM_Pos);	
	
	


MDR_PORTD -> FUNC |= (0x02 << PORT_FUNC_MODE13_Pos);
MDR_PORTD -> ANALOG |= (1 <<13);
MDR_PORTD -> PD &= ~ (1 << 13);
MDR_PORTD -> PWR |= (0x3 << PORT_PWR13_Pos);


//MDR_RST_CLK->TIM_CLOCK = RST_CLK_TIM_CLOCK_TIM2_CLK_EN;		
MDR_TIMER2 -> CH3_CNTRL1|= (0x2 << TIMER_CH_CNTRL1_NSELO_Pos);
MDR_TIMER2 -> CH3_CNTRL1|= (0x1 << TIMER_CH_CNTRL1_NSELOE_Pos);
MDR_TIMER2 ->CH3_CNTRL1 |= (0x1 << TIMER_CH_CNTRL1_NINV_Pos);	
MDR_TIMER2 -> CH3_CNTRL |= (0x6 << TIMER_CH_CNTRL_OCCM_Pos);	





MDR_PORTD -> FUNC |= (0x01 << PORT_FUNC_MODE14_Pos);
MDR_PORTD -> ANALOG |= (1 <<14);
MDR_PORTD -> PD &= ~ (1 << 14);
MDR_PORTD -> PWR |= (0x3 << PORT_PWR14_Pos);


//MDR_RST_CLK-> TIM_CLOCK = RST_CLK_TIM_CLOCK_TIM1_CLK_EN;		
MDR_TIMER1 -> CH4_CNTRL1|= (0x2 << TIMER_CH_CNTRL1_SELO_Pos);
MDR_TIMER1 -> CH4_CNTRL1|= (0x01 << TIMER_CH_CNTRL1_SELOE_Pos);	
MDR_TIMER1 -> CH4_CNTRL |= (0x6 << TIMER_CH_CNTRL_OCCM_Pos);	

MDR_TIMER1 -> CCR2 = 250;
MDR_TIMER2 -> CCR2 = 2750;
MDR_TIMER1 -> CCR3 = 8000;
MDR_TIMER2 -> CCR3 = 2750;
MDR_TIMER1 -> CCR4 = 250;	
	
	
}	